# VisionProcessor configuration

# Camera ID handled by this VisionProcessor instance.
#cam_id: 0

# Camera source type. Availability depending on libraries installed.
# SPINNAKER, IMAGES
source: IMAGES

# Spinnaker camera id
#spinnaker_id: 0

# List of image file system paths for IMAGES source.
#images: []
images:
- "test-data/rc2022/bots-balls-many-1/00000.png"
- "test-data/rc2022/bots-balls-many-1/00001.png"
- "test-data/rc2022/bots-balls-many-1/00002.png"
- "test-data/rc2022/bots-balls-many-1/00003.png"
#- "test-data/rc2019/1/cam0/00000.png"
#- "test-data/rc2019/1/cam0/00001.png"
#- "test-data/rc2019/1/cam0/00002.png"
#- "test-data/rc2019/1/cam0/00003.png"
#- "test-data/rc2022/bots-center-ball-1-0/00000.png"
#- "test-data/rc2022/bots-center-ball-1-0/00001.png"
#- "test-data/rc2022/bots-center-ball-1-0/00002.png"
#- "test-data/rc2022/bots-center-ball-1-0/00003.png"
#- "test-data/rc2022/bots-center-ball-1-1/00000.png"
#- "test-data/rc2022/bots-center-ball-1-1/00001.png"
#- "test-data/rc2022/bots-center-ball-1-1/00002.png"
#- "test-data/rc2022/bots-center-ball-1-1/00003.png"

# Default bot height in mm
#default_bot_height: 150.0

# Max tracked bot acceleration in m/s^2
#max_bot_acceleration: 6.5

# Max tracked ball velocity in m/s
#max_ball_velocity: 8.0

# Min tracking radius in mm
#min_tracking_radius: 30.0

# Vision multicast IP address
#vision_ip: "224.5.23.2"

# Vision multicast port
#vision_port: 10006

# Camera feed base port (cam_id is added to maintain separation)
#stream_base_port: 10100